const C=window.CEMARA_CONFIG||{};
const {createClient}=window.supabase||{};
let db=null,works=[],filter='Semua',selected=null,current=null,user=null,isAdmin=false,editing=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const date=x=>new Date(x).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});
function toast(x){const e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>e.classList.remove('show'),2200)}
function modal(id,on=true){$('#'+id).classList.toggle('open',on);document.body.style.overflow=$$('.modal-overlay.open').length?'hidden':''}
function ready(){return C.SUPABASE_URL&&!C.SUPABASE_URL.includes('YOUR-PROJECT')&&C.SUPABASE_PUBLISHABLE_KEY&&!C.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_')}
async function boot(){
 if(!ready()){ $('#worksGrid').innerHTML='<div class="empty-state"><div>⚙</div><h3>Supabase belum dikonfigurasi</h3><p>Isi <b>config.js</b> dengan Project URL dan Publishable Key.</p></div>';authUI();return; }
 db=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);
 const {data:{session}}=await db.auth.getSession();user=session?.user||null;await adminCheck();await loadWorks();authUI();
 db.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;await adminCheck();authUI();if(current)comments()});
}
async function adminCheck(){if(!db||!user){isAdmin=false;return}const {data}=await db.from('admin_profiles').select('user_id').eq('user_id',user.id).maybeSingle();isAdmin=!!data}
async function loadWorks(){const {data,error}=await db.from('works').select('*').order('published_at',{ascending:false});if(error){$('#worksGrid').innerHTML='<div class="empty-state"><h3>Gagal memuat karya</h3><p>'+esc(error.message)+'</p></div>';return}works=data||[];$('#workCount').textContent=String(works.length).padStart(2,'0');render()}
function render(){const q=$('#searchInput').value.trim().toLowerCase();const a=works.filter(w=>(filter==='Semua'||w.category===filter)&&(`${w.title} ${w.author} ${w.category} ${w.description}`.toLowerCase().includes(q)));$('#worksGrid').innerHTML=a.length?a.map(w=>`<article class="work-card"><button class="work-cover ${esc(w.cover)}" data-preview="${w.id}"><div class="cover-art">${esc(w.cover_symbol)}</div><div class="cover-text"><small>${esc(w.category)}</small><strong>${esc(w.title)}</strong></div></button><div class="work-info"><div class="work-category">${esc(w.category)}</div><h3>${esc(w.title)}</h3><p>${esc(w.description)}</p><div class="work-footer"><span class="author">${esc(w.author)} • ${date(w.published_at)}</span><div class="card-buttons"><button class="card-btn" data-preview="${w.id}">Detail</button><button class="card-btn eye" data-open="${w.id}" title="Buka karya">◉</button></div></div></div></article>`).join(''):'<div class="empty-state"><div>⌕</div><h3>Karya belum ditemukan</h3><p>Coba kata kunci atau kategori lain.</p></div>';
 $$('[data-preview]').forEach(b=>b.onclick=()=>preview(b.dataset.preview));$$('[data-open]').forEach(b=>b.onclick=()=>reader(b.dataset.open));}
function preview(id){selected=works.find(w=>w.id===id);if(!selected)return;$('#modalCategory').textContent=selected.category;$('#modalTitle').textContent=selected.title;$('#modalByline').textContent='Karya oleh '+selected.author;$('#modalDescription').textContent=selected.description;$('#modalDate').textContent='Dipublikasikan '+date(selected.published_at);$('#modalCover').className='modal-cover '+selected.cover;$('#modalCover').innerHTML='<span>'+esc(selected.cover_symbol)+'</span>';modal('workModal')}
function reader(id){current=works.find(w=>w.id===id);if(!current)return;$('#readerTitle').textContent=current.title;$('#readerBody').innerHTML=current.content.split(/\n+/).filter(Boolean).map((p,i)=>`<p class="${i===1?'quote':''}">${esc(p)}</p>`).join('');modal('workModal',false);editing=null;comments();modal('readerModal')}
async function comments(){if(!db||!current)return;const {data,error}=await db.from('comments').select('*').eq('work_id',current.id).order('created_at',{ascending:false});if(error){$('#commentsList').textContent=error.message;return}const a=data||[];$('#commentCount').textContent=a.length+' komentar';$('#commentAuthHint').textContent=user?'Login aktif. Komentar milikmu bisa diedit/dihapus.':'Kamu bisa berkomentar tanpa login. Login diperlukan untuk mengedit/menghapus komentar milikmu.';$('#commentsList').innerHTML=a.length?a.map(c=>{const can=isAdmin||(user&&c.user_id===user.id);return `<div class="comment-item"><div class="comment-top"><strong>${esc(c.name)}</strong><time>${date(c.created_at)}</time></div><p>${esc(c.content)}</p>${can?`<div class="comment-actions"><button data-edit="${c.id}">Edit</button><button data-del="${c.id}">Hapus</button></div>`:''}</div>`}).join(''):'<div class="empty-comments">Belum ada komentar. Jadilah yang pertama mengapresiasi karya ini ✦</div>';$$('[data-edit]').forEach(b=>b.onclick=()=>editComment(b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=()=>delComment(b.dataset.del))}
async function editComment(id){if(!user)return toast('Login dulu untuk mengedit komentar.');const {data}=await db.from('comments').select('*').eq('id',id).single();if(!data)return;editing=data;$('#commentName').value=data.name;$('#commentText').value=data.content;$('#commentText').focus();toast('Mode edit aktif.')}
async function delComment(id){if(!user)return toast('Login dulu untuk menghapus komentar.');if(!confirm('Hapus komentar ini?'))return;const {error}=await db.from('comments').delete().eq('id',id);if(error)toast(error.message);else{toast('Komentar dihapus.');comments()}}
$('#commentForm').onsubmit=async e=>{e.preventDefault();if(!db)return;const name=$('#commentName').value.trim(),content=$('#commentText').value.trim();if(!name||!content)return;if(editing){const {error}=await db.from('comments').update({name,content,updated_at:new Date().toISOString()}).eq('id',editing.id);if(error)toast(error.message);else{editing=null;e.target.reset();toast('Komentar berhasil diedit.');comments()}}else{const {error}=await db.from('comments').insert({work_id:current.id,user_id:user?.id||null,name,content});if(error)toast(error.message);else{e.target.reset();toast('Komentar tersimpan. ✦');comments()}}};
function authUI(){const e=$('#authView');if(!db){e.innerHTML='<p>Isi config.js terlebih dahulu.</p>';return}if(user){e.innerHTML=`<p>Masuk sebagai <b>${esc(user.email)}</b>.</p><div class="admin-note">${isAdmin?'Akun ini adalah admin CEMARA. Admin dapat mengelola karya dan semua komentar.':'Akun biasa: dapat mengedit/menghapus komentar milik sendiri.'}</div><button class="btn btn-ghost" id="logout">Keluar</button>`;$('#logout').onclick=async()=>{await db.auth.signOut();toast('Berhasil keluar.')};}else{e.innerHTML='<p>Login untuk mengelola komentar milikmu. Admin CEMARA menggunakan akun Supabase Auth.</p><form id="login" class="comment-form"><input id="email" type="email" required placeholder="Email"><input id="pass" type="password" required placeholder="Password"><button class="btn btn-primary">Masuk</button></form>';$('#login').onsubmit=async e=>{e.preventDefault();const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#pass').value});if(error)toast(error.message);else{toast('Berhasil masuk.');modal('adminModal',false)}}}}
$('#adminButton').onclick=()=>{authUI();modal('adminModal')};$$('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));$$('.modal-overlay').forEach(o=>o.onclick=e=>{if(e.target===o)modal(o.id,false)});$('#openWorkBtn').onclick=()=>selected&&reader(selected.id);$('#modalCommentBtn').onclick=()=>selected&&reader(selected.id);$('#searchInput').oninput=render;$$('.filter-btn').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter-btn').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#themeToggle').onclick=()=>{const d=document.documentElement.dataset.theme==='dark';if(d)delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme='dark';localStorage.setItem('cemara_theme',d?'light':'dark');$('#themeToggle').textContent=d?'☾':'☀'};if(localStorage.getItem('cemara_theme')==='dark'){document.documentElement.dataset.theme='dark';$('#themeToggle').textContent='☀'}
$('#backTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});addEventListener('scroll',()=>$('#backTop').classList.toggle('show',scrollY>500));$('#menuToggle').onclick=()=>$('.main-nav').classList.toggle('open');$$('.main-nav a').forEach(a=>a.onclick=()=>$('.main-nav').classList.remove('open'));$('#copyEmail').onclick=async()=>{try{await navigator.clipboard.writeText('duta.literasi@sekolah.sch.id');toast('Email disalin.')}catch{toast('duta.literasi@sekolah.sch.id')}};$('#year').textContent=new Date().getFullYear();document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal-overlay.open').forEach(x=>modal(x.id,false))});boot();
